version: '2.1'
services:
  ubotdb:
    image: postgres:latest
    #    ports:
    #      - 5432:5432
    environment:
      POSTGRES_PASSWORD: universa-pass
      POSTGRES_USER: root
    healthcheck:
      test: ["CMD","cat", "/var/tmp/db_init_completed.lock"]
      interval: 1s
      retries: 10
      timeout: 10s
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      net_16ubots:
        aliases:
          - ubotdb
        ipv4_address: 11.6.0.10
        ipv6_address: fdaa:745e:3098:5739::10
  ubot-0-local:
    image: universa/ubotserver:latest-debug
    command: --config /deploy/
    #entrypoint: tail -f /dev/null
    links:
     - ubotdb
    ports:
      - 17000:17000
    depends_on:
      ubotdb:
        condition: service_healthy
    volumes:
     - ./deploy/config/nodes/ubot_0.yaml:/deploy/config/config.yaml
     - ./deploy/config/mainnet_topology.json:/deploy/config/mainnet_topology.json
     - ./deploy/config/keys:/deploy/config/keys
     - ./deploy/config/nodes:/deploy/config/nodes
     - ./deploy/ubot0-tmp:/deploy/tmp
    environment:
      NODE_INDEX: 0
    networks:
      net_16ubots:
        aliases:
          - ubot0
        ipv4_address: 11.6.0.11
        ipv6_address: fdaa:745e:3098:5739::11
  ubot-1-local:
    image: universa/ubotserver:latest-debug
    command: --config /deploy/
    links:
      - ubotdb
    ports:
      - 17001:17001
    depends_on:
      ubotdb:
        condition: service_healthy
    volumes:
      - ./deploy/config/nodes/ubot_1.yaml:/deploy/config/config.yaml
      - ./deploy/config/mainnet_topology.json:/deploy/config/mainnet_topology.json
      - ./deploy/config/keys:/deploy/config/keys
      - ./deploy/config/nodes:/deploy/config/nodes
      - ./deploy/ubot1-tmp:/deploy/tmp
    environment:
      NODE_INDEX: 1
    networks:
      net_16ubots:
        aliases:
          - ubot1
        ipv4_address: 11.6.0.12
        ipv6_address: fdaa:745e:3098:5739::12
networks:
  net_16ubots:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet:  11.6.0.0/16
          gateway: 11.6.0.1
        # Generated using https://simpledns.com/private-ipv6
        - subnet:  fdaa:745e:3098:5739::/64
          gateway: fdaa:745e:3098:5739::1
        # IPs:     fdaa:745e:3098:5739:xxxx:xxxx:xxxx:xxxx
