# To build:
#   docker build --tag universa/node-u8:latest --compress -f docker/node-u8/Dockerfile .
#   docker push universa/node-u8

FROM universa/u8

ENTRYPOINT ["/u8/u8", "/code/u8scripts/node/node.js"]
