---
http_client_port: 17002
http_public_port: 17002
udp_server_port: 16002
database: host=ubotdb port=5432 dbname=ubot2db user=ubot2user password=uniPass
node_number: 2
public_host: localhost
node_name: ubot_2
ip:
- 127.0.0.1
ipv6:
  - fdf0:e132:efcf:2fae::13