---
http_client_port: 17001
http_public_port: 17001
udp_server_port: 16001
database: host=ubotdb port=5432 dbname=ubot1db user=ubot1user password=uniPass
node_number: 1
public_host: localhost
node_name: ubot_1
ip:
- 127.0.0.1
ipv6:
  - fdaa:745e:3098:5739::12