---
http_client_port: 17004
http_public_port: 17004
udp_server_port: 16004
database: host=ubotdb port=5432 dbname=ubot4db user=ubot4user password=uniPass
node_number: 4
public_host: localhost
node_name: ubot_4
ip:
- 127.0.0.1
ipv6:
  - fdaa:745e:3098:5739::15